In [1]:
import numpy as np

In [19]:
a = np.arange(3) # array with 3 integers, starting from the default integer 0.
print(a)

[0 1 2]


In [13]:
b = np.arange(0, 5) # array that starts from the integer 0, ends at 5. (arguments{start}, {end})
print(b)

[0 1 2 3 4]


In [17]:
c = np.arange(1, 20, 3) # array that starts from the integer 1, ends at 20, incremented by 3. (arguments{start}, {end}, {increments})
print(c)

[ 1  4  7 10 13 16 19]


### changing default type

In [25]:
c = np.arange(20, dtype = float) # changing default type
print(c)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]


In [ ]:
!jupyter --version