In [1]:
import numpy as np

In [2]:
a = np.arange(3) # array with 3 integers, starting from the default integer 0.
print(a)

[0 1 2]


In [3]:
b = np.arange(0, 5) # array that starts from the integer 0, ends at 5. (arguments{start}, {end})
print(b)

[0 1 2 3 4]


In [4]:
c = np.arange(1, 20, 3) # array that starts from the integer 1, ends at 20, incremented by 3. (arguments{start}, {end}, {increments})
print(c)

[ 1  4  7 10 13 16 19]


### changing default type

In [5]:
c = np.arange(20, dtype = float) # changing default type
print(c)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]


In [6]:
!jupyter --version 

Selected Jupyter core packages...
IPython          : 7.34.0
ipykernel        : 5.5.6
ipywidgets       : 8.1.5
jupyter_client   : 8.6.3
jupyter_core     : 5.7.2
jupyter_server   : 2.12.5
jupyterlab       : 3.6.8
nbclient         : 0.5.13
nbconvert        : 6.4.5
nbformat         : 5.10.4
notebook         : 6.5.4
qtconsole        : 5.6.1
traitlets        : 5.7.1
