In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

add = a + b
print(add)
sub = a - b
print(sub)
mul = a * b
print(mul)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [5]:
a = np.array([[1, 2, 3], [1, 2, 3]])
b = np.array([[4, 5, 6], [4, 5, 6]])

print(a)
print(b)

add = a + b
print(add)
sub = a - b
print(sub)
mul = a * b
print(mul)

[[1 2 3]
 [1 2 3]]
[[4 5 6]
 [4 5 6]]
[[5 7 9]
 [5 7 9]]
[[-3 -3 -3]
 [-3 -3 -3]]
[[ 4 10 18]
 [ 4 10 18]]
